export const GUJARAT_HC_CASE_MODES = [
    "REGISTRATION",
    "FILING",
    "CNR Number"
] as const;

export const GUJARAT_HC_CASE_TYPES = [
    "AO-APPEAL FROM ORDER",
    "CA-CIVIL APPLICATION",
    "CR-CIVIL REFERENCES",
    "CRA-CIVIL REVISION APPLICATION",
    "FA-FIRST APPEAL",
    "LPA-LETTERS PATENT APPEAL",
    "MCA-MISC. CIVIL APPLICATION",
    "MCACP-MISC. CIVIL APPLN. (CONTEMPT PETITION)",
    "SA-SECOND APPEAL",
    "SCA-SPECIAL CIVIL APPLICATION",
    "COMA-COMPANY APPLICATION",
    "COMP-COMPANY PETITION",
    "CS-CIVIL SUITS",
    "EA-ELECTION APPLICATION",
    "EP-ELECTION PETITION",
    "ITA-INCOME TAX APPLICATION",
    "ITR-INCOME TAX REFERENCE",
    "TAXAP-TAX APPEAL",
    "CR.A-CRIMINAL APPEAL",
    "CR.MA-CRIMINAL MISC.APPLICATION",
    "CR.RA-CRIMINAL REVISION APPLICATION",
    "SCR.A-SPECIAL CRIMINAL APPLICATION",
    "Other"
] as const;

export type GujaratHCCaseMode = typeof GUJARAT_HC_CASE_MODES[number];
export type GujaratHCCaseType = typeof GUJARAT_HC_CASE_TYPES[number];
